# Generated by Django 2.0.2 on 2018-03-18 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='Gift Reciever Full Name')),
                ('receiver_address', models.CharField(max_length=255, verbose_name='Gift Receiver Address')),
                ('receiver_phone_number1', models.CharField(max_length=30)),
                ('receiver_phone_number2', models.CharField(blank=True, max_length=30, null=True)),
                ('gift_date', models.DateField(help_text='Please specify when to deliver the gift')),
                ('gift_message', models.CharField(blank=True, help_text='Short message to be wrapped with your gift', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed')], default='pending', max_length=30)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift.Gift')),
            ],
            options={
                'ordering': ['payment_status', 'delivery_status'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(upload_to='products/thumbnails/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift.Catagory')),
            ],
            options={
                'verbose_name': 'Gift Package',
                'ordering': ['publish', '-updated_at', 'name'],
                'verbose_name_plural': 'Gift Packages',
            },
        ),
        migrations.CreateModel(
            name='PackagePictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='products/pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift.Package')),
            ],
            options={
                'ordering': ['package', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.ImageField(upload_to='payment_methods/thumbnails/')),
                ('publish', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='tags',
            field=models.ManyToManyField(to='gift.Tag'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='gift',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift.Package'),
        ),
        migrations.AddField(
            model_name='gift',
            name='user',
            field=models.ForeignKey(help_text='Gift Provider', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
